### ISSUE TITLE
Error in 0.0.14 release of SwingSet

### ISSUE THREAD

**Issue by katelynsills** [Agoric/SwingSet#84] opened 2019-06-20 23:54 UTC
In ERTP, when I upgrade to SwingSet version 0.0.14, I get the following error:

```
/Users/katelynsills/code/ertp/node_modules/@agoric/swingset-vat/src/controller.js:1
Error: Cannot find module './kvstore'
Require stack:
- /Users/katelynsills/code/ertp/node_modules/@agoric/swingset-vat/src/controller.js
- /Users/katelynsills/code/ertp/node_modules/@agoric/swingset-vat/src/index.js
- /Users/katelynsills/code/ertp/node_modules/@agoric/swingset-vat/src/main.js
- /Users/katelynsills/code/ertp/test/demo/test-demos.js
- /Users/katelynsills/code/ertp/node_modules/tape/bin/tape
    at Object.<anonymous> (/Users/katelynsills/code/ertp/node_modules/@agoric/swingset-vat/src/controller.js:1)
```

I think this might mean that the SwingSet bundle wasn't created before we published to npm. Could we re-release it?

**Comment by warner** [comment] 2019-06-21 00:28
huh, I think chris saw that error too, but I think it went away when he deleted `node_modules` and re-installed.. we didn't figure out the root cause. I'm happy to cut a new release, but let me look at the bundle file first and see if it changes when I do that. (I used `npm run-script pack ; npm run-script publish`, which should have rebuilt the bundle first).

**Comment by katelynsills** [comment] 2019-06-21 00:31
huh, it went away when I deleted node_modules. That's really strange.

**Comment by warner** [comment] 2019-06-21 00:33
I think we also observed that `controller.js` line 1 wasn't actually trying to import `kvstore`, the line was really somewhere else. We couldn't figure that out either.

**Comment by warner** [comment] 2019-06-21 02:27
so one weirdness I noticed: ERTP's `package.json` has a dependency on an older version (0.0.12) of swingset. `cosmic-swingset` depends on the current 0.0.14. If you've got an older install of cosmic-swingset, update to the most recent cosmic-swingset, and run `npm install`, it leaves `node_modules/@agoric/ertp/node_modules/@agoric/swingset-vat` at 0.0.12, but puts 0.0.14 in `node_modules/@agoric/swingset-vat`. Which means cosmic-swingset will get a different version than anything imported from ERTP.

If you delete `node_modules` and re-run `npm install`, I think it might decide that the `0.0.14` available in the root is good enough for ERTP, and then maybe they can both use the same version. But I'm really not sure.

I'm also not sure what our `rollup`-ifying code will do with this split-version situation, but it's unlikely to be good.

**Comment by warner** [comment] 2019-07-13 23:36
@michaelfig pointed out that there are ESM `.cache` directories scattered around, and they don't get updated as quickly as they're supposed to. So maybe the stale code was coming from an ESM-rewritten version of `controller.js`.

If someone runs into this again in the future, try locating and deleting just the `.cache` directories (with `find . -name .cache -print0 | xargs -0 rm -rf && npm install`, thanks to https://github.com/Agoric/SwingSet/pull/89#issuecomment-511155199), and see if that helps. They're all stored under `node_modules/`, so deleting the whole thing would also work, but it's a bit overkill.

**Comment by michaelfig** [comment] 2019-07-13 23:42
I've raised this in the ESM repository: [esm#746](https://github.com/standard-things/esm/issues/746#issuecomment-511160099)

**Comment by warner** [comment] 2019-07-13 23:56
Thanks. I think this is most likely the culprit, so I'll close this one now.

**Closed by warner** 2019-07-13 23:56 UTC

**Comment by warner** [comment] 2019-12-04 19:19
in the old repo. this was SwingSet issue 84
